language: 'php'
php:
  - '7.3'

before_install: false

install: 
      - composer install

before_script: true

script: 
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
    

after_script: true

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
